import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import { BLOCKS } from "@contentful/rich-text-types";
import Head from "next/head";
import Layout from "../../components/Layout";
import { getPost, getPosts, Post } from "../../services/content";

const renderOptions = {
  renderNode: {
    [BLOCKS.EMBEDDED_ASSET]: (node, children) => (
      <img src={node.data.target.fields.file.url}
        height={node.data.target.fields.file.details.height}
        width={node.data.target.fields.file.details.width}
        alt="Content Image"
      />
    ),
  }
}

type Props = {
  post: Post
}

export default function PostPage({ post }: Props) {
  return (
    <Layout title={post.fields.title}>
      <div>
        <Head>
          <title>{post.fields.title} | Coders Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="w-4/5 m-auto min-h-[21.5rem] p-14">
          <div className="w-full max-w-4xl m-auto">
            <img alt="Post thumbnail" src={post.fields.thumbnail.fields.file.url} className="w-full object-cover rounded-[1.875rem]" />
          </div>

          <div className="mt-5 whitespace-pre-wrap">
            {documentToReactComponents(post.fields.content, renderOptions)}
          </div>
        </div>
      </div>
    </Layout>
  )
}


export async function getStaticProps({ params }) {
  const post = await getPost(params.id);

  return {
    props: {
      post
    }
  }
}

export async function getStaticPaths() {
  const posts = await getPosts();

  return {
    paths: posts.map((post) => `/post/${post.sys.id}`),
    fallback: false,
  }
}